export const SET_COMMENTS = 'SET_COMMENTS';
export const SET_COMMENTS_IS_LOADING = 'SET_COMMENTS_IS_LOADING';
export const RESET_COMMENTS_IS_LOADING = 'RESET_COMMENTS_IS_LOADING';
export const SET_COMMENTS_ERROR = 'SET_COMMENTS_ERROR';